apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: fastapi-celery
spec:
  ports:
  - name: fastapi-app-port
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: fastapi-app
  type: LoadBalancer