apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: worker
  name: worker
  namespace: fastapi-celery
spec:
  replicas: 3
  selector:
    matchLabels:
      app: worker
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: worker
    spec:
      containers:
      - image: dpdan/fastapi-celery-example-worker:latest
        name: worker
        resources: {}
        envFrom:
          - configMapRef:
              name: env-configmap
          - secretRef:
              name: env-secret